# Generated by Django 5.0 on 2025-03-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='durqcao',
            field=models.TimeField(help_text='Duracaçao do record', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ritmo',
            field=models.TimeField(help_text='Ritmo realizado', verbose_name='Ritmo'),
        ),
    ]
