# Generated by Django 5.0 on 2025-03-11 00:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_app.basemodel')),
                ('name', models.CharField(help_text='Nome para a tag. Entre 5 e 200', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Descrição')),
            ],
            bases=('my_app.basemodel',),
        ),
    ]
