# Generated by Django 5.0 on 2025-03-11 01:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_app.basemodel')),
                ('descricao', models.CharField(help_text='Descrição de um exemplo', max_length=200, verbose_name='Descrição')),
                ('qualidade', models.IntegerField(help_text='Valor para qualidade do exemplo. Entre 0 e 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qualidade')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor para o balançeamento', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Balaço')),
            ],
            bases=('my_app.basemodel',),
        ),
    ]
